version: "3.8"

services:
  development:
    build: 
      context: ./
      target: development
    cap_add:
      - "CAP_SYS_PTRACE"
        #    ports:
      #      - "1-65535:1-65535" #forward ALL ports
      
    security_opt:
      - seccomp:unconfined
    volumes:
      #bind the development files into base
      - type: bind
        source: ./../
        target: /base
      #bind the nvim configuration files. 
      ##Can be omitted if read only config files are preferred
      #- type: bind
      #  source: ./lua
      #  target: /root/.config/nvim/lua
      #- type: bind
      #  source: ./spell
      #  target: /root/.config/nvim/spell
      #- type: bind
      #  source: ./init.lua
      #  target: /root/.config/nvim/init.lua
      #- type: bind
      #  source: ./.luarc.json
      #  target: /root/.config/nvim/.luarc.json
